name: iot-dev
channels:
- conda-forge
dependencies:
- python
- "taxcalc>=3.2.0"
- pandas
- numpy
- scipy
- setuptools
- pip
- pytest
- pytest-xdist
- pycodestyle
- pylint
- coverage
- pip:
  - jupyter-book>=0.9.1
  - black
  - plotly-express
  - kaleido
  - typing_extensions
  - jupyter-book
  - sphinxcontrib-bibtex