name: Build and test [Python 3.10, 3.11]

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Setup Miniconda using Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: iot-dev
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Build
        shell: bash -l {0}
        run: |
          pip install -e .
          pip install pytest-cov
          pip install pytest-pycodestyle
      - name: Test
        shell: bash -l {0}
        working-directory: ./
        run: |
          pytest -m 'not full_run and not regression' --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        if: contains(github.repository, 'PSLmodels/InverseOptimalTax')
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
