name: Check Black formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: psf/black@stable
        with:
          options: "--line-length 79 --check --verbose"
          src: "."
