name: Build and Deploy Jupyter Book documentation
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    if: github.repository == 'PSLmodels/InverseOptimalTax'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: iot-dev
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Build # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install jupyter-book
          pip install sphinxcontrib-bibtex==2.2.0
          pip install -e .
          cd docs
          jb build ./book

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/book/_build/html # The folder the action should deploy.
